services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    volumes:
      - ./volumes/minio:/export
    command: minio server /export --console-address ":9001"

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - etcd
      - minio

  app:
    build: .
    container_name: rag-app
    # Isso faz o Docker carregar o seu arquivo .env automaticamente
    env_file:
      - .env
    depends_on:
      - standalone
    environment:
      - MILVUS_HOST=standalone
    volumes:
      - .:/app
    # Essas duas linhas permitem que vocÃª interaja com o terminal (digite perguntas)
    stdin_open: true
    tty: true
